version: "3"

services:
  mysql:
    image: mysql:8
    restart: always
    volumes:
      - mysqldb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"

volumes:
  mysqldb:
