version: "3"

services:
  mysql:
    image: mysql:8.0.34
    restart: always
    volumes:
      - mysqldb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Rjirf3522
      MYSQL_DATABASE: panelDatabase
    ports:
      - "3306:3306"

volumes:
  mysqldb:
